import type { ProfileSummary } from '../types/api';
import { User, BookOpen, Code, Calculator, TrendingUp } from 'lucide-react';

interface ProfileInsightsProps {
  summaries: ProfileSummary;
}

const modeIcons = {
  writing: BookOpen,
  coding: Code,
  math: Calculator,
};

const modeLabels = {
  writing: 'Writing',
  coding: 'Coding',
  math: 'Math',
};

export function ProfileInsights({ summaries }: ProfileInsightsProps) {
  const { overallSummary, perMode } = summaries;

  return (
    <div className="flex-1 overflow-y-auto bg-white">
      <div className="max-w-4xl mx-auto p-6 space-y-8">
        {/* Header */}
        <div className="text-center">
          <div className="flex items-center justify-center mb-4">
            <User className="w-12 h-12 text-blue-600" />
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            Your Learning Insights
          </h1>
          <p className="text-gray-600">
            Track your progress and discover patterns in your learning journey
          </p>
        </div>

        {/* Overall Summary */}
        <section className="bg-gray-50 rounded-lg p-6">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            Overall Summary
          </h2>
          {overallSummary ? (
            <p className="text-gray-700 leading-relaxed">{overallSummary}</p>
          ) : (
            <div className="text-center py-8">
              <BookOpen className="w-16 h-16 text-gray-400 mx-auto mb-4" />
              <p className="text-gray-500">
                No learning summary available yet. Complete more sessions to generate insights!
              </p>
            </div>
          )}
        </section>

        {/* Mode-wise Summaries */}
        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-6">
            Mode-wise Summaries
          </h2>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {(Object.keys(modeLabels) as Array<keyof typeof modeLabels>).map((mode) => {
              const Icon = modeIcons[mode];
              const summary = perMode[mode];

              return (
                <div key={mode} className="bg-white border border-gray-200 rounded-lg p-6">
                  <div className="flex items-center mb-4">
                    <Icon className="w-6 h-6 text-blue-600 mr-3" />
                    <h3 className="text-lg font-semibold text-gray-900">
                      {modeLabels[mode]} Summary
                    </h3>
                  </div>
                  {summary ? (
                    <p className="text-gray-700 text-sm leading-relaxed">{summary}</p>
                  ) : (
                    <p className="text-gray-500 text-sm italic">
                      No summary available for {modeLabels[mode].toLowerCase()} yet.
                    </p>
                  )}
                </div>
              );
            })}
          </div>
        </section>

        {/* Recent Patterns - UI Only */}
        <section>
          <h2 className="text-xl font-semibold text-gray-900 mb-6 flex items-center">
            <TrendingUp className="w-6 h-6 text-green-600 mr-3" />
            Recent Patterns
          </h2>
          <div className="bg-white border border-gray-200 rounded-lg p-6">
            <div className="space-y-4">
              {/* Placeholder patterns - these would be generated by backend/Kestra later */}
              <div className="flex items-start space-x-3 p-3 bg-blue-50 rounded-lg">
                <div className="w-2 h-2 bg-blue-500 rounded-full mt-2 flex-shrink-0"></div>
                <p className="text-gray-700 text-sm">
                  Struggles with problem decomposition in coding challenges
                </p>
              </div>
              <div className="flex items-start space-x-3 p-3 bg-green-50 rounded-lg">
                <div className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0"></div>
                <p className="text-gray-700 text-sm">
                  Improved clarity in explaining mathematical concepts
                </p>
              </div>
              <div className="flex items-start space-x-3 p-3 bg-yellow-50 rounded-lg">
                <div className="w-2 h-2 bg-yellow-500 rounded-full mt-2 flex-shrink-0"></div>
                <p className="text-gray-700 text-sm">
                  Consistent engagement with writing practice sessions
                </p>
              </div>
            </div>
            <p className="text-xs text-gray-500 mt-4 italic">
              Patterns are analyzed from your recent learning sessions and will be updated as you progress.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
